// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdmQpBBFkISQFwyR9YiTOk6KPhFn7qdJM',
    appId: '1:386348362022:web:52d6bb491b682e3e5f79e7',
    messagingSenderId: '386348362022',
    projectId: 'todowithfirebase-87191',
    authDomain: 'todowithfirebase-87191.firebaseapp.com',
    storageBucket: 'todowithfirebase-87191.firebasestorage.app',
    measurementId: 'G-VREWR7Q7RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDq-LzXhh9npidXq8kq--PnaiW5gjIcE',
    appId: '1:386348362022:android:954196fb9e6752535f79e7',
    messagingSenderId: '386348362022',
    projectId: 'todowithfirebase-87191',
    storageBucket: 'todowithfirebase-87191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuHWjj_Qu7RcT8psFK-UUEF00Jk66gZQ',
    appId: '1:386348362022:ios:058adf3fd54cfba45f79e7',
    messagingSenderId: '386348362022',
    projectId: 'todowithfirebase-87191',
    storageBucket: 'todowithfirebase-87191.firebasestorage.app',
    iosBundleId: 'com.example.todoWithFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuHWjj_Qu7RcT8psFK-UUEF00Jk66gZQ',
    appId: '1:386348362022:ios:058adf3fd54cfba45f79e7',
    messagingSenderId: '386348362022',
    projectId: 'todowithfirebase-87191',
    storageBucket: 'todowithfirebase-87191.firebasestorage.app',
    iosBundleId: 'com.example.todoWithFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdmQpBBFkISQFwyR9YiTOk6KPhFn7qdJM',
    appId: '1:386348362022:web:c1e836da74a4f4cc5f79e7',
    messagingSenderId: '386348362022',
    projectId: 'todowithfirebase-87191',
    authDomain: 'todowithfirebase-87191.firebaseapp.com',
    storageBucket: 'todowithfirebase-87191.firebasestorage.app',
    measurementId: 'G-P848KWQFM8',
  );
}
